blank_issues_enabled: false
contact_links:
    - name: Ask a question (test)
      url: https://github.com/media/unitconversation/discussions/new?category=q-a
      about: Ask the community for help
    - name: Request a feature
      url: https://github.com/media/unitconversation/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/media/unitconversation/issues/new
      about: Report a reproducable bug
